# Course overview {.unnumbered}

```{r, echo=FALSE}
session_data <- cbind.data.frame(
  Date = c("2024.10.18", "2024.10.25", 
           "2024.11.08", "2024.11.15", "2024.11.22", "2024.11.29",
           "2024.12.06", "2024.12.13", "2024.12.20",
           "2025.01.10", "2025.01.17"),
  Block = c(rep("Getting started", 2), rep("Programming in R", 2), 
            rep("Data Science in R", 3), rep("Databases", 2), rep("GIS", 2)),
  Topic = c("Data and research data management",
            "Git and GitHub",
            "Introduction to R",
            "Best practices in programming",
            "Data Science Workflow",
            "Count data and seriation",
            "Compositional data",
            "Databases (I)",
            "Databases (II)",
            "GIS (I)",
            "GIS (II)")
)
```


## Details

040468 Datenmanagement und digitale Archäologie (ÜB, unterrichtet in Englisch) Übungen (3 CP)

**Time slot** / **_Zeitfenster_**: Fr 14-16 Uhr c.t.

**Place** / **_Ort_**: Raum 2

**Course instructors** / **_Kursleiter_**: Angourakis / Klingenberg

## **Course schedule**/**_Kursplan_**:

```{r, echo=FALSE}
knitr::kable(session_data, row.names = TRUE, align = c("c", "c", "l"))
```

## **Evaluation** / **_Kursbewertung_**

(Attendance and final examination)
