# Data and research data management

## Introduction to Research Data

### What is data? What is it for?

Data refers to factual information, often in quantitative or qualitative form, used as a basis for reasoning, discussion, or calculation. It serves as the foundational element for analysis and supports decision-making across diverse fields. In research, data helps to generate new insights, verify hypotheses, and contribute to the overall body of knowledge in a specific area.

### Archaeological Data: Particularities

In archaeology, data encompasses various types such as field notes, artefacts, images, geospatial coordinates, and more. By systematically collecting, organizing, and analysing this data, researchers can reconstruct past human behaviours, understand environmental contexts, and explore cultural practices.

Archaeological data is unique due to its diverse formats and the complexity of its collection. It often includes material remains like pottery, bones, tools, and structures, as well as environmental data like pollen samples and soil types. Since archaeological data often comes from excavation sites, it is usually non-renewable; once excavated, a site cannot be restored to its original state.

Archaeologists rely heavily on careful documentation to preserve as much information as possible for future study. Furthermore, the context in which artefacts are found is crucial, as it helps interpret their use, significance, and the broader cultural setting.

### Open Science

Open Science promotes transparency and collaboration in research by making methodologies, data, and findings accessible to the public and other researchers. In archaeology, this can involve sharing excavation reports, datasets, and analysis methods to facilitate wider understanding and scrutiny of findings.

### FAIR Principles

FAIR stands for Findable, Accessible, Interoperable, and Reusable. These principles aim to enhance the usefulness of digital assets by ensuring they can be easily located, understood, and utilized by others. Applying FAIR principles in archaeology involves creating well-documented, open-access datasets that other researchers can readily use.

### Open Source

Open Source refers to software and tools that are freely available for anyone to use, modify, and distribute. For archaeologists, open-source tools can offer affordable solutions for data analysis, visualization, and data management, promoting a more inclusive research environment.

### Reproducibility

Reproducibility refers to the ability to replicate the results of a study using the original author's assets or following their methodology. It ensures that findings can be independently verified under similar conditions, reinforcing the reliability of scientific research [@national_academies_of_sciences_understanding_2019].

In scientific research, reproducibility is crucial for confirming the validity of experimental findings and building upon existing knowledge. It enhances transparency and trustworthiness in scientific practices, promoting better peer review and collaboration [@baker_1500_2016,@noauthor_grn_nodate].

Most research in archaeology does not necessarily involve controlled experiments and archaeological survey and excavation are destructive, thus unrepeatable. However, the reproducibility of data collection, processing and analysis is not a trivial concern.

Making research reproducible must be considered as a spectrum of practices, in which researchers should thrive for doing better, despite the challenges [@marwick_open_2017].

```{=html}
<iframe src="https://mfr.osf.io/render?url=https%3A%2F%2Fosf.io%2Fdownload%2F9bru3%2F%3Fdirect%26mode%3Drender" width="100%" scrolling="yes" height="300px" marginheight="0" frameborder="0" allowfullscreen webkitallowfullscreen></iframe>
<a href="https://doi.org/10.17605/OSF.IO/3D6XX" target="_blank">Ben Marwick, CC-By Attribution 4.0 International, available at OSF</a>
```

### The lay of the land: Organizations, tools, data repositories and where to find them

Several organizations and platforms support Open Science and the use of FAIR and Open Source principles, providing archaeologists with access to valuable tools and datasets:

- Organizations:

  - [OpenAIRE](https://www.openaire.eu/): OpenAIRE AMKE is a non-profit organization with a mission to promote open scholarship and improve discoverability, accessibility, shareability, reusability, reproducibility, and monitoring of data-driven research results, globally [@iatropoulou_openaire_nodate]. 
  - [Go FAIR Initiative](https://www.go-fair.org/): Provides guidelines on implementing FAIR principles, with resources tailored for researchers in various fields, including archaeology [@noauthor_fair_nodate].
  - [The Turing Way](https://github.com/the-turing-way/the-turing-way): collaborative writing of an online handbook [@community_turing_2022].
  - [CAA](https://caa-international.org/): Computer Applications and Quantitative Methods in Archaeology (CAA) is an international organisation bringing together archaeologists, mathematicians, and computer scientists. CAA counts with [National Chapters](https://caa-international.org/national-chapters/), including one for [Germany](https://ag-caa.de/).

- Data Repositories and Tools:  
  - [Zenodo](https://zenodo.org/): A repository where researchers can deposit datasets, software, and publications.  
  - [Open Science Foundation](https://osf.io/): OSF is a free, open platform to support your research and enable collaboration. 
  - [Archaeology Data Service (ADS)](https://archaeologydataservice.ac.uk/): An archive for archaeological data from the UK, which provides access to various datasets, including excavation reports and geospatial data.  
  - [Open Context](https://opencontext.org/): A platform offering access to archaeological data from various global sources, adhering to FAIR principles [noauthor_open_nodate-1].
  - [GitHub](https://github.com/): GitHub is a developer platform that allows developers to create, store, manage and share their code through the use of Git software and a series of additional automated services.

- Open Source Tools:  
  - [Markdown](https://www.markdownguide.org/): Markdown is a lightweight markup language designed for creating formatted text using a plain-text editor [@noauthor_markdown_nodate].  
  - [R](https://www.r-project.org/) and [Python](https://www.python.org/): Programming languages with extensive libraries for data analysis, which are widely used in archaeology for statistical analysis and modeling [@r_core_team_r_2024, noauthor_welcome_2024]. See more about these and other programming languages below.  
  - [RStudio](https://posit.co/download/rstudio-desktop/): RStudio IDE is an integrated development environment for R, a programming language for statistical computing and graphics.
  - [Quarto](https://quarto.org/): An open-source scientific and technical publishing system.
  - [Git](https://git-scm.com/): Git is a distributed version control system designed for tracking changes in source code during software development.
  - [Zotero](https://www.zotero.org/): Zotero is a free, easy-to-use tool to help collect, organize, annotate, cite, and share metadata on references.  
  - [QGIS](https://qgis.org/): A free, open-source GIS tool useful for mapping and spatial analysis in archaeology [@noauthor_spatial_nodate].
  
By utilizing these resources, archaeologists can ensure that their research aligns with Open Science, FAIR, and Open Source principles, ultimately enhancing the transparency, accessibility, and longevity of their work.

## Introduction to Programming for Research

### What is Programming?
Programming is the process of designing and implementing instructions that a computer can follow to perform specific tasks. It involves writing code in various programming languages that communicate with the computer's hardware and software to solve problems, process data, and automate repetitive tasks. At its core, programming is about creating a sequence of steps, known as algorithms, which help achieve a desired outcome [@noauthor_what_2024].

### Importance of Learning Programming

For researchers, learning programming offers several significant advantages:

- *Efficiency and Automation*: Programming can help automate data collection, processing, and analysis, saving time and reducing human error. It also enables researchers to handle large datasets and complex calculations with ease.

- *Reproducibility*: Writing scripts to perform analysis allows other researchers to replicate experiments, thus ensuring results can be verified and reproduced, a fundamental aspect of scientific research.

- *Access to Powerful Tools*: With programming skills, researchers can access a wide range of tools for data visualization, statistical analysis, machine learning, and simulation. These tools can enhance the scope and quality of research projects.

### Overview of Common Programming Languages

Several programming languages are popular in research due to their specific features and libraries[@noauthor_introduction_2018]:

- *Python*: Known for its readability and versatility, Python is widely used for data analysis, machine learning, and automation. It has extensive libraries such as NumPy, pandas, and matplotlib, which are particularly useful for data-intensive research.

- *R*: A language specifically developed for statistical computing and graphics, R is preferred in data science, bioinformatics, and fields requiring extensive statistical analysis. The Comprehensive R Archive Network (CRAN) offers thousands of packages that can handle a range of analytical tasks.

- *MATLAB*: Commonly used in engineering and scientific research, MATLAB excels at numerical computing, simulation, and algorithm development. It is particularly popular in fields like physics, engineering, and finance.

- *JavaScript*: While primarily a web development language, JavaScript is also used in research for developing interactive data visualizations and web-based applications.

### Concept of Research Software: Tools and Scripts

Research software comprises tools, libraries, and scripts that aid in conducting and managing research activities. It can range from simple scripts for data cleaning and preprocessing to complex software packages for statistical analysis and simulation. Although any software used in research could be considered as research software, advance training focus on programming or scripting skills, not on graphical user interface operations (e.g., creating a plot in R or Python rather than in Microsoft Excel).

- *Tools*: Research software tools like [Jupyter Notebooks](https://jupyter.org/), [RStudio](https://posit.co/download/rstudio-desktop/), [PyCharm](https://www.jetbrains.com/pycharm/), [Visual Studio Code](https://code.visualstudio.com/download), etc., offer integrated development environments (IDEs) tailored to a specific range of languages, enhancing productivity and facilitating code sharing and version control.

- *Scripts*: Scripts are text files encoding programs written to perform specific tasks. In research, scripts are often used for data cleaning, model training, and result visualization. Scripts can be used even to generate and format an entire dataset (have a peek on how the [course schedule has been built with R code](https://github.com/Andros-Spica/rub-archwiss_040468-data-management/blob/main/index.qmd)). These scripts can be shared among researchers to ensure that analyses are reproducible and consistent.

Learning programming for research allows scientists to leverage these tools and scripts effectively, making research more efficient, reproducible, and insightful.

### Where to learn (and keep learning)

* [Datacamp](https://www.datacamp.com) [@noauthor_learn_nodate]
* [Udemy](https://www.udemy.com/) [@noauthor_online_nodate]
* [Coursera](https://www.coursera.org/) [@noauthor_coursera_nodate]
* Courses and workshops by high education institutions (e.g,, [RUB Research School](https://www.research-school.rub.de/))

::: {.callout-note icon=false}
## Hands-on Practice {.unnumbered}

* Task 1: register yourself as user at:  
  * [GitHub](https://github.com/)  
  * [Zenodo](https://zenodo.org/)  
  * [Zotero](https://www.zotero.org/) (optional)  
* Task 2: installations:  
  * [Git](https://git-scm.com/). Follow general instructions [here](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) ([de](https://git-scm.com/book/de/v2/Erste-Schritte-Git-installieren)) or a video step-by-step tutorial like [this](https://youtu.be/iYkLrXobBbA?si=zDjSLzlRFQzEfdsr)) or [this (de)](https://youtu.be/Df_d46YDkEc?si=Q9sQU4kbmudbziy0), among many available online. 
  * [GitHub Desktop](https://desktop.github.com/download/)  
  * [R](https://www.r-project.org/)
  * [RStudio](https://posit.co/download/rstudio-desktop/)
  * [QGIS](https://qgis.org/)
* Task 3: explore datasets at [Open Context](https://opencontext.org/)
* Task 4: try writing a short document in markdown at [Markdown Live Preview](https://markdownlivepreview.com/). 
:::
